### ISSUE TITLE
Add tile blocker clearing and energy budgeting 

### ISSUE THREAD

**Issue by Goldziher** [Goldziher/Stellaris-Modding-Den#15]
We ought to add tile blocker clearing since the AI cannot do more than 1 tile blocker at a time, although it will do this whenever it can. We should also consider using the energy budgeting for stuff like terraforming. This is a function I'd like to use for planets enhanced, so we can cross use it in those two mods.

**Comment by Gra-tak** [comment]
player only and not in first release
